name: loopzilla_habit_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: Louis George
      fonts:
        - asset: assets/fonts/Louis-George-Cafe-Light.ttf
        - asset: assets/fonts/Louis-George-Cafe.ttf
        - asset: assets/fonts/Louis-George-Cafe-Bold.ttf
        - asset: assets/fonts/Naked-Bold.otf
        - asset: assets/fonts/Notion-HeavyItalic.otf
        - asset: assets/fonts/Notion-Medium.otf

  uses-material-design: true

  assets:
    - assets/