// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkgCkVPwTEkN3bBtlLq6B6C22kaFuiiGw',
    appId: '1:124675368424:web:8edba7d3e13320bbfab05d',
    messagingSenderId: '124675368424',
    projectId: 'loopzilla-10fa8',
    authDomain: 'loopzilla-10fa8.firebaseapp.com',
    storageBucket: 'loopzilla-10fa8.firebasestorage.app',
    measurementId: 'G-3TW7HZ3WHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMMlbeYEMitDQiQaFGcV0ZsAm_Q7xGzIM',
    appId: '1:124675368424:android:26ddaaa6cda3520afab05d',
    messagingSenderId: '124675368424',
    projectId: 'loopzilla-10fa8',
    storageBucket: 'loopzilla-10fa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA22zelDV0CJkiGoltEBAQAu01rs1M3gfw',
    appId: '1:124675368424:ios:568dc5e21c410abcfab05d',
    messagingSenderId: '124675368424',
    projectId: 'loopzilla-10fa8',
    storageBucket: 'loopzilla-10fa8.firebasestorage.app',
    iosBundleId: 'com.example.loopzillaHabitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA22zelDV0CJkiGoltEBAQAu01rs1M3gfw',
    appId: '1:124675368424:ios:568dc5e21c410abcfab05d',
    messagingSenderId: '124675368424',
    projectId: 'loopzilla-10fa8',
    storageBucket: 'loopzilla-10fa8.firebasestorage.app',
    iosBundleId: 'com.example.loopzillaHabitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkgCkVPwTEkN3bBtlLq6B6C22kaFuiiGw',
    appId: '1:124675368424:web:49d9a2fccd7ea1b0fab05d',
    messagingSenderId: '124675368424',
    projectId: 'loopzilla-10fa8',
    authDomain: 'loopzilla-10fa8.firebaseapp.com',
    storageBucket: 'loopzilla-10fa8.firebasestorage.app',
    measurementId: 'G-05T69V0XXG',
  );
}
